import { useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, TrendingUp, Sparkles, Award, Building2, Download, Share2 } from "lucide-react";
import ScoreBar from "../components/ScoreBar";
import CompanyCard from "../components/CompanyCard";

export default function ResultPage() {
  const { state } = useLocation();
  const navigate = useNavigate();

  const handleExport = () => {
    if (!state) return;
    
    // Create a formatted text report
    const reportContent = `
AI PLACEMENT PREDICTOR - RESULTS REPORT
========================================

ATS SCORE: ${state.ats_score}%
Status: ${state.ats_score >= 75 ? 'Excellent' : state.ats_score >= 50 ? 'Good' : 'Needs Work'}

TOP COMPANY MATCHES (${state.recommendations.length} roles)
========================================

${state.recommendations.map((role, i) => `
${i + 1}. ${role.company_name} - ${role.role_title}
   Fit Score: ${role.fit_score}/100
   
   Strengths:
${role.strengths.map(s => `   • ${s}`).join('\n')}
   
   Areas to Develop:
${role.gaps.map(g => `   • ${g}`).join('\n')}
   
   Summary: ${role.summary}
   
`).join('\n---\n')}

Generated by AI Placement Predictor
Report Date: ${new Date().toLocaleString()}
`;

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `placement-results-${new Date().getTime()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (!state) return;
    
    const shareText = `I just analyzed my resume with AI Placement Predictor!\n\n🎯 ATS Score: ${state.ats_score}%\n📊 Found ${state.recommendations.length} matching roles\n\nTop Match: ${state.recommendations[0]?.company_name} - ${state.recommendations[0]?.role_title} (${state.recommendations[0]?.fit_score}/100 fit score)`;
    
    // Check if Web Share API is available
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My AI Placement Predictor Results',
          text: shareText,
        });
      } catch (err) {
        if (err.name !== 'AbortError') {
          // Fallback to clipboard
          copyToClipboard(shareText);
        }
      }
    } else {
      // Fallback to clipboard for browsers without Share API
      copyToClipboard(shareText);
    }
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text).then(() => {
      alert('Results copied to clipboard! You can now paste and share.');
    }).catch(() => {
      alert('Could not copy to clipboard. Please try again.');
    });
  };

  if (!state) return (
    <div className="flex items-center justify-center h-screen bg-gradient-to-br from-sky-50 via-white to-sky-100">
      <div className="text-center bg-white p-8 rounded-2xl shadow-xl border border-sky-100">
        <div className="bg-sky-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
          <Sparkles className="w-8 h-8 text-sky-600" />
        </div>
        <h2 className="text-2xl font-bold text-gray-800 mb-2">No Results Found</h2>
        <p className="text-gray-600 mb-6">Please upload a resume to see your analysis</p>
        <button 
          onClick={() => navigate("/")} 
          className="bg-gradient-to-r from-sky-500 to-blue-600 hover:from-sky-600 hover:to-blue-700 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 shadow-lg hover:shadow-xl"
        >
          Go to Upload
        </button>
      </div>
    </div>
  );

  const { ats_score, recommendations } = state;

  return (
    <div className="min-h-screen bg-gradient-to-br from-sky-50 via-white to-sky-100 relative overflow-hidden">
      {/* Decorative Background Elements */}
      <div className="absolute top-0 right-0 w-96 h-96 bg-sky-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
      <div className="absolute bottom-0 left-0 w-96 h-96 bg-blue-200 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>

      <div className="relative z-10 max-w-7xl mx-auto p-6 py-8">
        {/* Header Section */}
        <div className="mb-8">
          <button 
            onClick={() => navigate("/")} 
            className="group flex items-center gap-2 text-sky-600 hover:text-sky-700 font-medium mb-6 transition-all duration-300 bg-white/60 backdrop-blur-sm px-4 py-2 rounded-lg shadow-sm hover:shadow-md border border-sky-100"
          >
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            Upload Another Resume
          </button>

          <div className="bg-white/80 backdrop-blur-sm rounded-3xl shadow-2xl border border-sky-100 p-8">
            <div className="flex items-center gap-4 mb-4">
              <div className="bg-gradient-to-br from-sky-400 to-blue-600 p-3 rounded-xl shadow-lg">
                <Award className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold bg-gradient-to-r from-sky-600 to-blue-600 bg-clip-text text-transparent">
                  Your Results
                </h1>
                <p className="text-gray-600 mt-1">AI-powered resume analysis complete</p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3 mt-6">
              <button 
                onClick={handleExport}
                className="flex items-center gap-2 bg-sky-50 hover:bg-sky-100 text-sky-700 px-4 py-2 rounded-lg font-medium transition-all duration-300 border border-sky-200 hover:shadow-md"
              >
                <Download className="w-4 h-4" />
                Export Results
              </button>
              <button 
                onClick={handleShare}
                className="flex items-center gap-2 bg-sky-50 hover:bg-sky-100 text-sky-700 px-4 py-2 rounded-lg font-medium transition-all duration-300 border border-sky-200 hover:shadow-md"
              >
                <Share2 className="w-4 h-4" />
                Share
              </button>
            </div>
          </div>
        </div>

        {/* ATS Score Section */}
        <div className="mb-8">
          <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-sky-100 p-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="bg-sky-100 p-2 rounded-lg">
                <TrendingUp className="w-6 h-6 text-sky-600" />
              </div>
              <h2 className="text-2xl font-bold text-gray-800">ATS Compatibility Score</h2>
            </div>
            
            <div className="bg-gradient-to-br from-sky-50 to-blue-50 rounded-xl p-6 border border-sky-100">
              <ScoreBar label="ATS Score" score={ats_score} />
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
                <div className="bg-white rounded-lg p-4 shadow-sm border border-sky-100">
                  <p className="text-sm text-gray-600 mb-1">Your Score</p>
                  <p className="text-2xl font-bold text-sky-600">{ats_score}%</p>
                </div>
                <div className="bg-white rounded-lg p-4 shadow-sm border border-sky-100">
                  <p className="text-sm text-gray-600 mb-1">Industry Average</p>
                  <p className="text-2xl font-bold text-gray-700">68%</p>
                </div>
                <div className="bg-white rounded-lg p-4 shadow-sm border border-sky-100">
                  <p className="text-sm text-gray-600 mb-1">Status</p>
                  <p className={`text-2xl font-bold ${ats_score >= 75 ? 'text-green-600' : ats_score >= 50 ? 'text-yellow-600' : 'text-red-600'}`}>
                    {ats_score >= 75 ? 'Excellent' : ats_score >= 50 ? 'Good' : 'Needs Work'}
                  </p>
                </div>
              </div>

              {/* Score Interpretation */}
              <div className="mt-6 p-4 bg-white rounded-lg border border-sky-100">
                <p className="text-sm font-semibold text-gray-700 mb-2">What this means:</p>
                <p className="text-sm text-gray-600">
                  {ats_score >= 75 
                    ? "Your resume is highly optimized for ATS systems. It should pass most automated screenings successfully."
                    : ats_score >= 50
                    ? "Your resume has good compatibility with ATS systems, but there's room for improvement to maximize your chances."
                    : "Your resume may face challenges with ATS systems. Consider optimizing formatting, keywords, and structure."
                  }
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Company Matches Section */}
        <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-sky-100 p-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-sky-100 p-2 rounded-lg">
              <Building2 className="w-6 h-6 text-sky-600" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-800">Top Company Matches</h2>
              <p className="text-gray-600 text-sm mt-1">
                Based on your skills, experience, and career goals
              </p>
            </div>
          </div>

          {recommendations && recommendations.length > 0 ? (
            <>
              <div className="mb-6 p-4 bg-gradient-to-r from-sky-50 to-blue-50 rounded-xl border border-sky-100">
                <div className="flex items-center gap-2 mb-2">
                  <Sparkles className="w-5 h-5 text-sky-600" />
                  <p className="font-semibold text-gray-800">
                    Found {recommendations.length} matching {recommendations.length === 1 ? 'role' : 'roles'}
                  </p>
                </div>
                <p className="text-sm text-gray-600">
                  These positions align with your profile and have high placement potential
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {recommendations.map((role, i) => (
                  <CompanyCard key={i} role={role} index={i} />
                ))}
              </div>
            </>
          ) : (
            <div className="text-center py-12 bg-sky-50 rounded-xl border border-sky-100">
              <Building2 className="w-12 h-12 text-sky-300 mx-auto mb-3" />
              <p className="text-gray-600">No company matches found</p>
            </div>
          )}
        </div>

        {/* Tips Section */}
        <div className="mt-8 bg-gradient-to-br from-sky-500 to-blue-600 rounded-2xl shadow-xl p-8 text-white">
          <div className="flex items-start gap-4">
            <div className="bg-white/20 p-3 rounded-xl">
              <Sparkles className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-xl font-bold mb-2">Pro Tips</h3>
              <ul className="space-y-2 text-sky-50">
                <li className="flex items-start gap-2">
                  <span className="text-white font-bold mt-0.5">•</span>
                  <span>Tailor your resume for each application by including relevant keywords from the job description</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-white font-bold mt-0.5">•</span>
                  <span>Use standard section headings (Experience, Education, Skills) for better ATS compatibility</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="text-white font-bold mt-0.5">•</span>
                  <span>Quantify your achievements with numbers and metrics whenever possible</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <style>{`
        @keyframes blob {
          0%, 100% { transform: translate(0, 0) scale(1); }
          25% { transform: translate(20px, -50px) scale(1.1); }
          50% { transform: translate(-20px, 20px) scale(0.9); }
          75% { transform: translate(50px, 50px) scale(1.05); }
        }
        
        .animate-blob {
          animation: blob 7s infinite;
        }
        
        .animation-delay-2000 {
          animation-delay: 2s;
        }
      `}</style>
    </div>
  );
}